spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: (username)
      password: (password)
      database: (database)
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
      password: (password)

app:
  security:
    jwt-secret-key: (jwt_secret)
    access-token-expirations-hour: 4
    refresh-token-expirations-hour: 168
