spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: username
      password: password
      database: template
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
      password: password

app:
  jwt:
    secret: secret
    expirationDay: 30
