spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: sondaehyeon01
      password: RootMJ0616!~
      database: template
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
      password: RootMJ0616!~

app:
  jwt:
    secret: secret
    expirationDay: 30
