server:
  servlet:
    encoding:
      force-response: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
    redis:
      host: localhost
      port: 6379
  mvc:
    log-resolved-exception: false

app:
  security:
    jwt-secret-key: (SECRET)
    access-token-expirations-hour: 4
    refresh-token-expirations-hour: 168
